title: KubeDaily
markdown: kramdown
url: "kubedaily.com"
baseurl: ""

# for atom feed
author:
  name: Sangam Biradar
  email: kubedaily@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-redirect-from
theme: jekyll-theme-minimal
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from

collections_dir: all_collections
collections:
  posts:
    output: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "post"
    permalink: /:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
